### ISSUE TITLE
fix: doesn't build?

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/website#12]
```
eseidel@erics-mbp website % docker compose up --build
[+] Building 5.8s (9/9) FINISHED                                                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                                                                    0.0s
 => => transferring dockerfile: 31B                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                       0.0s
 => => transferring context: 34B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/node:lts                                                                                                                                             0.4s
 => [1/4] FROM docker.io/library/node:lts@sha256:671ee8d49ce2a691fc3082203c5deb9522e0c80042aa0ff40c07f4a25e63668a                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                       0.0s
 => => transferring context: 30.56kB                                                                                                                                                                    0.0s
 => CACHED [2/4] WORKDIR /app                                                                                                                                                                           0.0s
 => [3/4] COPY . .                                                                                                                                                                                      0.1s
 => [4/4] RUN npm install                                                                                                                                                                               4.3s
 => exporting to image                                                                                                                                                                                  0.9s 
 => => exporting layers                                                                                                                                                                                 0.9s 
 => => writing image sha256:251f71226b0c7d7f65d202285609f10f0392d0a23da2b6d2debcb025b1ba39e9                                                                                                            0.0s 
 => => naming to docker.io/library/website-shorebird-site                                                                                                                                               0.0s 
[+] Running 1/0                                                                                                                                                                                              
 ⠿ Container shorebird-site  Recreated                                                                                                                                                                  0.1s 
Attaching to shorebird-site
shorebird-site  | 
shorebird-site  | > website@0.0.1 start
shorebird-site  | > astro dev --host 0.0.0.0
shorebird-site  | 
shorebird-site  |   🚀  astro  v2.3.1 started in 77ms
shorebird-site  |   
shorebird-site  |   ┃ Local    http://localhost:3000/
shorebird-site  |   ┃ Network  http://172.19.0.2:3000/
shorebird-site  |   
shorebird-site  | Error: The following dependencies are imported but could not be resolved:
shorebird-site  | 
shorebird-site  |   react-markdown (imported by /app/src/components/FAQ.tsx)
shorebird-site  | 
shorebird-site  | Are they installed?
shorebird-site  |     at file:///app/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:44125:23
shorebird-site  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
shorebird-site  |     at async file:///app/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:43534:38
```

**Comment by eseidel** [comment]
I ran npm install.  But maybe there is something else needed?

**Comment by eseidel** [comment]
I see it in the package.json:
    "react-markdown": "^8.0.7",

**Comment by eseidel** [comment]
Maybe I have to force my docker container to rebuild since it has its own `npm install`?

**Comment by felangel** [comment]
> Maybe I have to force my docker container to rebuild since it has its own `npm install`?

Yeah I think you need to rebuild the image

**Comment by bryanoltman** [comment]
Wouldn't the `--build` flag have trigged a rebuild?

**Comment by eseidel** [comment]
--force-recreate didn't fix:
```eseidel@erics-mbp website % docker compose up --build --force-recreate
[+] Building 0.5s (9/9) FINISHED                                                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                                                                    0.0s
 => => transferring dockerfile: 31B                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                       0.0s
 => => transferring context: 34B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/node:lts                                                                                                                                             0.4s
 => [1/4] FROM docker.io/library/node:lts@sha256:671ee8d49ce2a691fc3082203c5deb9522e0c80042aa0ff40c07f4a25e63668a                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                       0.0s
 => => transferring context: 24.72kB                                                                                                                                                                    0.0s
 => CACHED [2/4] WORKDIR /app                                                                                                                                                                           0.0s
 => CACHED [3/4] COPY . .                                                                                                                                                                               0.0s
 => CACHED [4/4] RUN npm install                                                                                                                                                                        0.0s
 => exporting to image                                                                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                                                 0.0s
 => => writing image sha256:251f71226b0c7d7f65d202285609f10f0392d0a23da2b6d2debcb025b1ba39e9                                                                                                            0.0s
 => => naming to docker.io/library/website-shorebird-site                                                                                                                                               0.0s
[+] Running 1/1
 ⠿ Container shorebird-site  Recreated                                                                                                                                                                  0.1s
Attaching to shorebird-site
shorebird-site  | 
shorebird-site  | > website@0.0.1 start
shorebird-site  | > astro dev --host 0.0.0.0
shorebird-site  | 
shorebird-site  |   🚀  astro  v2.3.1 started in 82ms
shorebird-site  |   
shorebird-site  |   ┃ Local    http://localhost:3000/
shorebird-site  |   ┃ Network  http://172.19.0.2:3000/
shorebird-site  |   
shorebird-site  | Error: The following dependencies are imported but could not be resolved:
shorebird-site  | 
shorebird-site  |   react-markdown (imported by /app/src/components/FAQ.tsx)
shorebird-site  | 
shorebird-site  | Are they installed?
shorebird-site  |     at file:///app/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:44125:23
shorebird-site  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
shorebird-site  |     at async file:///app/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:43534:38```

Will keep looking.

**Comment by eseidel** [comment]
Removed the image, rebuilt, still fails.  Not sure. 🤷   Can look on monday.
